# Generated by Django 3.0.5 on 2020-08-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20200801_0459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='recommendation',
            new_name='recommendation_text',
        ),
    ]
