# Generated by Django 3.0.5 on 2020-08-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_auto_20200801_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='aqirequestlog',
            name='location_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
