# Generated by Django 3.0.5 on 2020-08-01 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_aqirequestlog_location_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AQIRequestLog',
            new_name='AQIRecommendations',
        ),
    ]
