# Generated by Django 3.0.5 on 2020-08-01 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_auto_20200801_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('follow_up', models.TextField()),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.Recommendation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
