# Generated by Django 3.0.5 on 2020-10-17 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_followupquestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='description',
        ),
    ]
