# Generated by Django 3.0.5 on 2020-11-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_auto_20201107_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='end_time',
            field=models.TimeField(default='2020-11-08T11:59:59+05:45'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_time',
            field=models.TimeField(default='2020-11-08T05:00:00+05:45'),
        ),
    ]
