# Generated by Django 3.0.5 on 2020-11-08 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_auto_20201107_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='end_time',
            field=models.TimeField(default='2020-11-08T11:59:59+05:45'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_time',
            field=models.TimeField(default='2020-11-08T05:00:00+05:45'),
        ),
        migrations.CreateModel(
            name='SubscriptionMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.IntegerField()),
                ('delivery_location_name', models.CharField(max_length=200)),
                ('delivery_aqi', models.IntegerField()),
                ('subscription_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
