# Generated by Django 3.0.5 on 2020-11-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_auto_20201108_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiondelivery',
            name='delivery_status_message',
            field=models.TextField(blank=True),
        ),
    ]
